# ---------------------------------
# Cleanup Task
# ---------------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---

# ---------------------------------
# Nose Task
# ---------------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: ""
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/bash
        set -eux
        # Use /tekton/home for pip cache and --user installs
        export PIP_CACHE_DIR=/tekton/home/.cache/pip
        export PYTHONUSERBASE=/tekton/home/.local
        export PATH=$PYTHONUSERBASE/bin:$PATH
        python -m pip install --upgrade pip wheel
        pip install --user -r requirements.txt
        nosetests $(params.args)

---

# ---------------------------------
# Git Clone Local Task
# ---------------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-local
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
      description: Repository URL
    - name: revision
      type: string
      description: Branch, tag, or commit
      default: main
    - name: deleteExisting
      type: string
      default: "true"
  steps:
    - name: clone
      image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:75d6228eb656b8778fb3bb8dc68c686ac1c9b787e5343ae3c2467f8e724af83e
      workingDir: $(workspaces.output.path)
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        set -eux
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf $(workspaces.output.path)/*
        fi
        git clone --branch $(params.revision) $(params.url) $(workspaces.output.path)

---

# ---------------------------------
# Flake8 Local Task
# ---------------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-local
spec:
  workspaces:
    - name: source
  params:
    - name: image
      type: string
      default: docker.io/alpine/flake8@sha256:bb280bf2af4a434be912f25bbcb6c79ea4d735ed3c8e259f96c405998920871f
    - name: path
      type: string
      default: .
    - name: requirements_file
      type: string
      default: requirements.txt
    - name: args
      type: string
      default: ""
  steps:
    - name: lint
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        set -eux
        # Set pip cache and user install dir to /tekton/home
        export PIP_CACHE_DIR=/tekton/home/.cache/pip
        export PYTHONUSERBASE=/tekton/home/.local
        export PATH=$PYTHONUSERBASE/bin:$PATH
        python -m pip install --upgrade --user pip wheel
        pip install -r $(params.requirements_file)
        flake8 $(params.path) $(params.args)
---

# ---------------------------------
# Kaniko Task for OpenShift Restricted SCC
# ---------------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build-restricted
spec:
  workspaces:
    - name: source
    - name: docker-config
      description: Workspace for Kaniko credentials
      optional: true
  params:
    - name: IMAGE
      type: string
      description: Full image name (e.g., image-registry.openshift-image-registry.svc:5000/namespace/app:tag)
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
  stepTemplate:
    securityContext:
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.source.path)
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home
      script: |
        #!/busybox/sh
        set -eux

        /kaniko/executor \
          --dockerfile="$(params.DOCKERFILE)" \
          --context="$(workspaces.source.path)" \
          --destination="$(params.IMAGE)" \
          --docker-config=/tekton/home/.docker \
          --skip-tls-verify \
          --insecure \
          --verbosity=info
  volumes:
    - name: docker-config
      emptyDir: {}


